<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3_slack"
 *
 * Auto generated by Extension Builder 2017-04-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TYPO3 to Slack',
    'description' => 'Connect TYPO3 with Slack',
    'category' => 'plugin',
    'author' => 'Sven Jürgens',
    'author_email' => 't3@blue-side.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
